### ISSUE TITLE
CityScope blocks need to return NAICS codes

### ISSUE THREAD

**Issue by crisjf** [CityScope/CS_Urban_Indicators#15]
I lost track of the discussion on standardization, but I think we agree that the blocks returned in geogrid_data will include NAICS information. Is this so? @doorleyr ?

**Comment by doorleyr** [comment]
Yes and LBCS. The idea is to define each CS_type in this way:
https://github.com/CityScope/cityscope.github.io/blob/ronan/docs/md/Land-Use-Types.md

The type definitions are static and stored in the properties of the GEOGRID on cityI/O. When performing updates we parse the GEOGRIDDATA and for each grid-cell, look up the "name" to get the type definition. In the last commit, I added the type_definitions as an attribute of the handler which is also passed to the indicators when they are added to the handler.

Since the attributes are defined using multi-levels of nesting with percentages: a common task will be aggregating all the cells to get the total capacity by each NAICS code and each LBCS code. I'm now going to add another method to the indicator_tools to do this.

**Comment by crisjf** [comment]
I saw! I'm linking the commit for future reference:
eafa2ca24dd32ef0d7ce06317ede3317a851c63a

Ok! So the `name` property of each cell, which is currently empty, should be matched to the type defined in 'GEOGRID/properties/types'. Got it! 

Could we populate the 'GEOGRIDDATA' with some of the types we have, even if it is random, to test? That way I can finish writing the `grid_to_industries` function in the `EconomicIndicatorBase` (which is currently a placeholder).

**Comment by doorleyr** [comment]
Ok latest commit (53f0a3f1084229c811533456d158578f700e948c) has the new methods for parsing attributes of grid types. I also populated the GEOGRIDDATA with some of the correct types. Let me know if this works for you.

**Comment by crisjf** [comment]
I will have a look later this week! I'll close this issue for now. Thanks @doorleyr !
