### ISSUE TITLE
Redundant repeating attr at every point 

### ISSUE THREAD

**Issue by RELNO** [CityScope/CS_Urban_Indicators#9]
in the context of https://github.com/CityScope/CS_cityscopeJS/issues/65, 

![Screen Shot 2020-03-27 at 20 55 08](https://user-images.githubusercontent.com/14296774/77810901-594a2900-706d-11ea-9dd6-206fe85698e3.png)

^ these attr appear on every access cell. Instead, array of values `[0.4, 0.1....]` with a dictionary at the upper level (`geometry:{}, attributes:{}...`)  will reduce json size quite dramatically.

**Comment by doorleyr** [comment]
Transferred the issue to this repo because accessibility is now integrated in the Urban_indicators repo as the proximity indicator. 
I've updated the proximity indicator as suggested by @RELNO above. The structure of the resulting geojson is now:
{
"type": "FeatureCollection",
"properties": {"attributes": ["restaurants', "shopping", ...],
"features": [
....
]
}

However, the properties seem to be stripped out of the geojson by the handler before being sent to cityIO. @crisjf is it possible to stop this from happening?

**Comment by RELNO** [comment]
@doorleyr cool thanks --  didn't know moving issues is a feature. Would make sense to therefore remove the old repo, I know HCU and others were looking into it and it might create some confusion

**Comment by crisjf** [comment]
See issue #8 that was reopened

**Comment by crisjf** [comment]
Will close this as we are fixing this in #8
